### ISSUE TITLE
Pairing/Bonding planned?

### ISSUE THREAD

**Issue by mmueller-kaffeeschluerfercom** [nettlep/gobbledegook#28]
Hi! Thanks for the great code!! Do you have any plans to integrate pairing/bonding some time?
Best regards

**Comment by nettlep** [comment]
Unfortunately not.

I created this library for use in a personal project and that project's functionality eventually grew to the point that BLE was no longer a good fit. The BLE code was removed and replaced with a TCP solution. Because of that, I no longer have a usable use case for GGK.

I think I need to start hunting for a new maintainer.
