### ISSUE TITLE
Dependency for building on Raspberry Pi Stretch

### ISSUE THREAD

**Issue by gmatrangola** [nettlep/gobbledegook#3]
The documentation on this is great! But, you might want to consider having a section on dependencies. I needed to install automake and libbluetooth-dev before it would build on Raspbian Stretch. The ./configure script noticed that I didn't have automake, but I didn't realize that I needed libbluetooth-dev until it started the compile. 

Also, you mention that you build it on 5.45. It seems to work fine on the default install of 5.43 that comes with Raspbian Stretch. (with --expiremental enabled) Is there anything that I should be aware of with that older version?

**Comment by nettlep** [comment]
Good point about the libbluetooth-dev dependency. I'll add that in the next update. I'm not sure how I missed that one.

As for the version, I haven't tested against various versions of BlueZ, but the key issue is support for D-Bus. You shouldn't need `--experimental` flag on 5.43 since, according to the BlueZ site, D-Bus support was [no longer considered experimental as of version 5.42](http://www.bluez.org/release-of-bluez-5-42/).
